#!/usr/bin/env node

// this file is stored in a directory of APP_ROOT/script for me, all things are relative to that
var APP_ROOT = process.cwd()+"/";   // __dirname + "/../";

// this assumes there is a file stored in APP_ROOT called "config.js" with the following structure: 
//
// module.exports = {
//  "development": {
//    "postgresql": "tcp://postgres@localhost/dev-db"
//  },
//  "staging": {
//    "postgresql": "tcp://postgres@localhost/stage-db"
//  },
//  "production": {
//    "postgresql": "tcp://postgres@localhost/db"
//  }
// }
//
// It also assumes you have a directory "migrations" on the APP_ROOT where this is run. 
// If you have a default schema, file must be at "migrations/root/schema.sql"



// get the current environment (for handling development, staging, production environments)
var app_env = process.env["NODE_ENV"] || "development";

// load configuration data for the specified environment
var app_config = require(APP_ROOT + "config.js")[app_env];

var migrator = require(__dirname+"/lib/migrator");

migrator.migrate(APP_ROOT, app_config);
